runtime: python27
api_version: 1
threadsafe: true

handlers:
    - url: /
      static_files: .out/index.html
      upload: .out/index.html

    - url: /(.*)
      static_files: .out/\1
      upload: .out/(.*)
